---
title: Tutorial Übersicht
format: html
filters:
  - pyodide
---


# Kurven Diskussion mit Python realisieren

Auf dieser Webseite soll dir anhand eines dir bekannten Themas Python näher gebracht werden.  

:::{.callout-note title="Für ein paar Tipps zur Nutzung des Tutorials hier klicken!" collapse="true"}
*Solche klickbaren Blöcke wird es immer mal wieder im Tutorial geben, um das Ganze ein wenig übersichtlicher zu machen, oder aber um evtl. bekanntes Wissen für Nutzende, die dieses bereits haben auszublenden.*  
<details>
<summary> Hier klicken! </summary>
_Auch diese Form der klickbaren Blöcke wird aus ähnlichen Gründen im Tutorial erscheinen, sie kann aber im Gegenzug zum oberen keine Icons enthalten._
</details>

**Linksseitig** siehst du eine Übersicht über das ganze Tutorial.  
Du kannst die einzelnen Abschnitt auf-/zu klappen.  
Das Tutorial ist dafür gemacht von oben bis unten nacheinander durchgearbeitet zu werden. Beim Überspringen von Kapiteln/Unterkapiteln kann es daher sein, dass weiteres nicht verstanden wird.  

**Rechtsseitig** siehst du die Übersicht über die Seite, auf der du bist. Das heißt, hier kannst du die einzelnen Überschriften des Unterkapitels sehen und direkt dorthin springen.  

**Oben** in der Leiste erkennst du mehrere Symbole. Die <i class="fa-solid fa-magnifying-glass"></i> ist die Suchfunktion, mit der du im ganzen Tutorial nach einem Begriff suchen kannst. Mit dem <i class="fa-solid fa-circle-half-stroke"></i>-Symbol kannst du zwischen Light- und Dark-Mode wechseln. Das <i class="fa-solid fa-book-open-reader"></i>-Symbol aktiviert den *Reader-Mode*, der die Seitenleisten ausblendet, um dir ein ungestörtes Lesen zu ermöglichen.

:::

**Ziel des Tutorials:**  
Das Tutorial soll dir, als Nutzende Person, Python ein wenig näher bringen mithilfe des Abitur Themas der Kurvendiskussion.  
Hierbei werden Schritt für Schritt die Schritte der Kurvendiskussion durchgegangen und jeweils gezeigt, wie diese Schritte mit Python umgesetzt werden können.  

In diesem Tutorial werden oft **Code-Blöcke** wie die folgenden auftauchen, das sind **Pyodide-Python-Blöcke**, sie sind ausführbar mit dem #Pfeilsymbol(dreieck nach rechts spitz) und führen den Code der in ihnen steht aus.  
```{pyodide-python}
#| read-only: true
#Manche Code Blöcke kannst du nicht bearbeiten
print("Hello World!")
```

```{pyodide-python}
#Andere Code-Blöcke kannst du bearbeiten
print("Hello World?")
#Ändere als Test gerne "Hello World?" zu der Ausgabe deiner Wahl.
```

Solche Felder erstellen eine Python Umgebung.  
Das heißt in ihnen kannst du wie in Python programmieren!  

:::{.callout-tip title="Weiteres zu den Code-Blöcken"}
**Weitere Code-Blöcke erzeugen** kannst du mit dem "Add New Codeblock" Button erzeugen.  
**Ki-Feedback** zu deinem Code kannst du mit dem Feedback Button erzeugen, hierfür musst du jedoch oben eine Base-Url und einen API-Key angegeben haben.
:::
